./PDFPlotter CT10_F0_lep.txt MSTW_F0_lep.txt NNPDF_F0_lep.txt
./PDFPlotter CT10_FL_lep.txt MSTW_FL_lep.txt NNPDF_FL_lep.txt
./PDFPlotter CT10_FR_lep.txt MSTW_FR_lep.txt NNPDF_FR_lep.txt
./PDFPlotter CT10_F0_had.txt MSTW_F0_had.txt NNPDF_F0_had.txt
./PDFPlotter CT10_FL_had.txt MSTW_FL_had.txt NNPDF_FL_had.txt
./PDFPlotter CT10_FR_had.txt MSTW_FR_had.txt NNPDF_FR_had.txt
./PDFPlotter CT10_F0_lephad.txt MSTW_F0_lephad.txt NNPDF_F0_lephad.txt
./PDFPlotter CT10_FL_lephad.txt MSTW_FL_lephad.txt NNPDF_FL_lephad.txt
./PDFPlotter CT10_FR_lephad.txt MSTW_FR_lephad.txt NNPDF_FR_lephad.txt